### ISSUE TITLE
Remove dependence on LowRankApprox.jl?

### ISSUE THREAD

**Issue by dlfivefifty** [MikaelSlevinsky/FastTransforms.jl#53]
LowRankApprox.jl has a very large compile time and memory usage, due to the many `mul!` overrides involving `StridedArray`s.

This will surely be fixed in time, but in the meantime, how hard would it be to remove the dependence here?

Another option would be to rewrite LowRankApprox.jl using LazyArrays. This has proven very successful for BandedMatrices: as of yesterday compile is down from 30s / 7GB to 2s / 100MB. But I think it's best to minimise the investment into that design.

**Comment by MikaelSlevinsky** [comment]
I'm not so concerned about compilation time because I don't often edit `LowRankApprox`, but long `using` time for `FastTransforms` is annoying.

This package uses `idfact!`, the types `IDPackedV`, `LRAOptions`, and `ColumnPermutation`, and some `mul!` functions, though most (all?) of the ones actually in use are defined here since the butterfly requires index shifts.

**Comment by MikaelSlevinsky** [comment]
Maybe we can make a call to the Julia community (https://discourse.julialang.org/t/fourth-weekly-upgradathon-friday-today-july-20-2018/12540) to show `LowRankApprox` some love?

**Comment by dlfivefifty** [comment]
But it's already upgraded for Julia v1.0 ...

**Comment by MikaelSlevinsky** [comment]
And the `using` time is satisfactory? How could a performance regression of `(18.936 s)/(2.1504 s) = 8.8x` go unnoticed?

**Comment by dlfivefifty** [comment]
I just pushed a fix! now `using FastTransforms` is only 6s
